# Generated by Django 4.2.5 on 2023-10-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='form',
            field=models.CharField(max_length=100, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
    ]
