# Generated by Django 4.2.5 on 2023-10-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0002_alter_studentmodel_form_alter_studentmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='username'),
        ),
    ]
