# Generated by Django 4.2.5 on 2023-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0003_studentmodel_username_teachermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='chat_id',
            field=models.CharField(max_length=100, null=True, verbose_name='chat_id'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='chat_id',
            field=models.CharField(max_length=100, null=True, verbose_name='chat_id'),
        ),
    ]
